---
title: "R Notebook"
output: html_notebook
---

LOADING PACKAGES

```{r}
library("DESeq2")
library(dplyr)
library(stringr)
library(apeglm)
library(ggplot2)
library("EnhancedVolcano")
library("tidyr")
library(edgeR)
library(patchwork)
library(Biostrings)
library("seqinr")
library(vegan)
library(ape)
```

LOADING FILES

```{r}
# load metadata
SRRs <- read.csv("PRJNA524877.csv", header = TRUE)
# add columns for the state and time point of each run
SRRs <- SRRs %>%
  mutate(State = ifelse(str_detect(Sample.Name, "Control"), "control", "infected"),
      time_point = str_extract(Sample.Name, "\\d+")
    )

# load gene counts for each run
cts <- read.table("defense-infection-transcriptomics-QC2-feature-counts-summary.tsv", header = TRUE)
names(cts)[names(cts) == "run_accession"] <- "Run"
# select runs from PRJNA524877 (because also contains runs from PRJNA524872)
cts <- cts %>% filter(Run %in% SRRs$Run) %>%
  mutate(Gene_origin = ifelse(grepl("^NZ", Chr), "Bacteria", "Phage"))

# load defense systems for Vibrio cyclitrophicus obtained from defense finder
ds <- read.csv("defense_systems.csv", header = TRUE)[, c("Geneid", "protein_in_syst", "type")]
```

EDA

```{r}
# Number of bacterial and phage gene counts per run
cts_per_run_b_p <- cts %>%
  left_join(SRRs, by = "Run") # join with SRR to get the condition to label

cts_per_run_b_p <- cts_per_run_b_p %>%
  group_by(Library.Name, Gene_origin) %>%
  summarise(counts = sum(counts), .groups = "drop") %>%
  as.data.frame() 
colnames(cts_per_run_b_p)[colnames(cts_per_run_b_p) == "Library.Name"] <- "Run"
# Add a Time column with the time after infection
cts_per_run_b_p$Time <- str_extract(cts_per_run_b_p$Run, "\\d+")
# One sample was taken before infection so had no time given in the metadata
cts_per_run_b_p$Time <- replace_na(cts_per_run_b_p$Time, "0-")

# number of gene counts per run
cts_per_run <- cts_per_run_b_p %>%
  group_by(Time) %>%
  summarise(counts = sum(counts), .groups = "drop") 
```

```{r}
# Bar plot number of gene counts per run
par(mgp = c(3, 0.2, 0))
barplot(cts_per_run$counts, main = "Number of reads per run", names.arg = cts_per_run$Time, ylab = "# reads", xlab = "Time after infection (min)", col = "darkblue", border = NA, las = 2, cex.names = 0.7, cex.axis = 0.8)

# Box plot number of gene counts per run
boxplot(cts_per_run$counts, main = "Number of reads per run distribution", ylab = "# reads", col = "darkblue", las =1, cex.axis = 0.8)

# Compute coefficient of variation (SD / mean)
# <0.2 so fairly homogenous
CV <- sd(cts_per_run$counts)/mean(cts_per_run$counts)
```

```{r}
# Plots bacteria and phage gene counts per run 
ggplot(cts_per_run_b_p, aes(x = Time, y = counts, fill = Gene_origin)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Phage" = "darkgreen", "Bacteria" = "darkblue")) +
  theme_minimal() +
  labs(
    x = "Time after infection (min)",
    y = "# genes counted in the sample",
    fill = "Gene origin"
  ) +
  theme(
    axis.text.x = element_text(angle = 90) 
)

# Compute coefficient of variation (SD / mean) for bacteria gene counts
# CV >0.2 very heterogenous gene count among samples !
CV_bacteria <- sd(cts_per_run_b_p[cts_per_run_b_p$Gene_origin == "Bacteria", ]$counts)/mean(cts_per_run_b_p[cts_per_run_b_p$Gene_origin == "Bacteria", ]$counts)
```

```{r}
# Construction of a distance matrix for PCoA
dist_matrix_cts <- cts[c("Run", "Geneid", 'counts')] %>%
  group_by(Run, Geneid) %>%
  pivot_wider(
    names_from = Run,
    values_from = counts, 
    values_fill = 0
  ) %>%
  as.data.frame()

rownames(dist_matrix_cts) <- dist_matrix_cts$Geneid
dist_matrix_cts <- dist_matrix_cts[ , -1]

dist_matrix_cts <- vegdist(t(dist_matrix_cts), method = "euclidean")

# Compute principal coordinate decomposition
pcoa <- pcoa(dist_matrix_cts)

# Plot PCoA2 vs PCoA2
pcoa_df <- data.frame(
  Run = rownames(pcoa$vectors),
  Axis1 = pcoa$vectors[, 1],
  Axis2 = pcoa$vectors[, 2]
)
pcoa_df <- left_join(pcoa_df, SRRs, by = "Run")
pcoa_df <- pcoa_df %>%
  mutate(
    label = paste0(ifelse(State == "infected", "I", "C"), " ", time_point)
  )

ggplot(pcoa_df, aes(x = Axis1, y = Axis2, color = State, label = label)) +
  geom_point(size = 4) +
  geom_text(vjust = -0.8, size = 3.5, color = "black") +
  scale_color_manual(
    values = c("infected" = "darkgreen",  
               "control" = "darkblue")   
  ) +
  theme_minimal() +
  labs(
    x = paste0("PCoA 1 (", round(pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA 2 (", round(pcoa$values$Relative_eig[2] * 100, 1), "%)"),
    color = "Condition")
```

COUNT MATRIX

```{r}
cnt_matrix <- cts[cts$Gene_origin == "Bacteria", ] %>% # filter bacteria genes
  left_join(SRRs, by = "Run") %>%
  mutate(condition = paste(State, time_point, sep = "_")) %>%
  select(Geneid, condition, counts) %>%
  pivot_wider(names_from = condition,
              values_from = counts,
              values_fill = 0) %>%
  as.data.frame()

cnt_matrix$Geneid <- gsub("^cds-", "", cnt_matrix$Geneid)
rownames(cnt_matrix) <- cnt_matrix$Geneid
cnt_matrix <- cnt_matrix[ , -1]
```

FUNCTION DESEQ + VOLCANO PLOT (control vs infected)

```{r}
# columns of cnt_matrix to select
cols <- c("infected_0", "infected_NA", "infected_15", "infected_30", "infected_45", "infected_60", "infected_75", "infected_90", "infected_105", "infected_120")


# construction of DESeq dataset
# preinfection and infection at time 0 were taken as control replicates
# all samples after infection (whatever the time) were taken as replicates
coldata <- data.frame(
  row.names = cols,
  condition = factor(c("control", "control", "infected", "infected", "infected", "infected", "infected", "infected", "infected", "infected"))
)

countData <- round(cnt_matrix[,cols])

dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = coldata,
                              design = ~ condition)

# differential expression analysis
dds <- DESeq(dds)
res <- as.data.frame(results(dds, alpha = 0.1, pAdjustMethod = "fdr"))

# label for defense genes 
labels <- rownames(res) %>%
  as.data.frame() %>%
  `colnames<-`("protein_in_syst") %>%
  left_join(ds, by = "protein_in_syst") %>%
  mutate(label = ifelse(is.na(type), "", type)) %>%
  pull(label)

# add column labels (character and logical)
res <- mutate(res, label=labels)
res <- mutate(res, ds = factor(res$label != ""))

# plot -Log10 FDR vs Log fold change
plot <- ggplot(res, aes(x = log2FoldChange, y = -log10(padj), color = ds)) +
  geom_point(data = subset(res, ds == "FALSE"), color = "grey", alpha = 0.3) +
  geom_point(data = subset(res, ds == "TRUE"), color = "darkgreen") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +
  geom_label_repel(data = subset(res, ds == "TRUE" & padj < 0.05),
      aes(label = label), 
      size = 3, 
      max.overlaps = Inf, 
      show.legend = NA,
      colour = "black"
) +
  xlim(-5, 5) +
  ylim(0, 10) +
  annotate("text", x=-3, y=10, label =  "control vs infected") +
  theme_bw()
```

```{r}
plot
```
