---
title: "R Notebook"
output: html_notebook
---

LOADING PACKAGES

```{r}
library("DESeq2")
library(dplyr)
library(stringr)
library(apeglm)
library(ggplot2)
library("EnhancedVolcano")
library("tidyr")
library(edgeR)
library(patchwork)
library(Biostrings)
library("seqinr")
library(vegan)
library(ape)
library(tibble)
library(patchwork)
```

LOADING FILES

```{r}
# load metadata
SRRs <- read.csv("metadata.csv", header = TRUE)
# add columns for the state and time point of each run
SRRs <- SRRs %>%
  mutate(State = ifelse(str_detect(Sample.Name, "Control"), "control", "infected"),
      time_point = str_extract(Sample.Name, "\\d+")
    )

# load gene counts for each run
cts <- read.table("counts.tsv", header = TRUE)
names(cts)[names(cts) == "run_accession"] <- "Run"
# select runs from PRJNA524872 (because also contains runs from PRJNA524877)
cts <- cts %>% filter(Run %in% SRRs$Run) %>%
  mutate(Gene_origin = ifelse(grepl("^NZ", Chr), "Bacteria", "Phage"))
cts$Geneid <- sub("^cds-", "", cts$Geneid)

# load defense systems for Vibrio cyclitrophicus obtained from defense finder
ds <- read.csv("defense_systems.csv", header = TRUE)[, c("Geneid", "protein_in_syst", "type")]
```

EDA

```{r}
# Number of bacterial and phage gene counts per run
cts_per_run_b_p <- cts %>%
  left_join(SRRs, by = "Run") # join with SRR to get the condition to label

cts_per_run_b_p <- cts_per_run_b_p %>%
  group_by(Library.Name, Gene_origin) %>%
  summarise(counts = sum(counts), .groups = "drop") %>%
  as.data.frame()
colnames(cts_per_run_b_p)[colnames(cts_per_run_b_p) == "Library.Name"] <- "Run"

# number of gene counts per run
cts_per_run <- cts_per_run_b_p %>%
  group_by(Run) %>%
  summarise(counts = sum(counts), .groups = "drop") 
```

```{r}
# Bar plot number of gene counts per run
par(mgp = c(3, 0.2, 0))
barplot(cts_per_run$counts, main = "Number of reads per run", names.arg = cts_per_run$Run, ylab = "# reads", col = "darkblue", border = NA, las = 2, cex.names = 0.7, cex.axis = 0.8)

# Box plot number of gene counts per run
boxplot(cts_per_run$counts, main = "Number of reads per run distribution", ylab = "# reads", col = "darkblue", las =1, cex.axis = 0.8)

# Compute coefficient of variation (SD / mean)
# >0.2 so not homogenous
CV <- sd(cts_per_run$counts)/mean(cts_per_run$counts)
```

```{r}
# Plots bacteria and phage gene counts per run 
ggplot(cts_per_run_b_p, aes(x = Run, y = counts, fill = Gene_origin)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Phage" = "red", "Bacteria" = "darkblue")) +
  theme_minimal() +
  labs(
    x = "Run",
    y = "# reads",
    fill = "Gene origin"
  ) +
  theme(
    axis.text.x = element_text(angle = 90) 
)
```

```{r}
# Construction of a distance matrix for PCoA
dist_matrix_cts <- cts[c("Run", "Geneid", 'counts')] %>%
  group_by(Run, Geneid) %>%
  pivot_wider(
    names_from = Run,
    values_from = counts, 
    values_fill = 0
  ) %>%
  as.data.frame()

rownames(dist_matrix_cts) <- dist_matrix_cts$Geneid
dist_matrix_cts <- dist_matrix_cts[ , -1]

dist_matrix_cts <- vegdist(t(dist_matrix_cts), method = "euclidean")

# Compute principal coordinate decomposition
pcoa <- pcoa(dist_matrix_cts)

# Plot PCoA2 vs PCoA2
pcoa_df <- data.frame(
  Run = rownames(pcoa$vectors),
  Axis1 = pcoa$vectors[, 1],
  Axis2 = pcoa$vectors[, 2]
)
pcoa_df <- left_join(pcoa_df, SRRs, by = "Run")
pcoa_df <- pcoa_df %>%
  mutate(
    label = paste0(ifelse(State == "infected", "I", "C"), " ", time_point)
  )

ggplot(pcoa_df, aes(x = Axis1, y = Axis2, color = State, label = label)) +
  geom_point(size = 4) +
  geom_text(vjust = -0.8, size = 3.5, color = "black") +
  scale_color_manual(
    values = c("infected" = "red",  
               "control" = "darkblue")   
  ) +
  theme_minimal() +
  labs(
    x = paste0("PCoA 1 (", round(pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA 2 (", round(pcoa$values$Relative_eig[2] * 100, 1), "%)"),
    color = "Condition")
```

COUNT MATRIX

```{r}
cnt_matrix <- cts[cts$Gene_origin == "Bacteria", ] %>% 
# filter bacteria genes   
left_join(SRRs, by = "Run") %>%   
  mutate(condition = paste(State, time_point, sep = "_")) %>%   
  select(Geneid, condition, counts) %>%   
  pivot_wider(names_from = condition,               
              values_from = counts,               
              values_fill = 0) %>%   
  as.data.frame()  
cnt_matrix$Geneid <- gsub("^cds-", "", cnt_matrix$Geneid) 
rownames(cnt_matrix) <- cnt_matrix$Geneid 
cnt_matrix <- cnt_matrix[ , -1] 
cnt_matrix <- cnt_matrix[, order(names(cnt_matrix))]
```

CLR

```{r}
# Transform the cts_matrix dataframe into a Deseq object
dds_for_vst <- DESeqDataSetFromMatrix(round(cnt_matrix), as.data.frame(colnames(cnt_matrix)), design = ~ 1)
# Apply a variance stabilizing transformation (VST) to the count data
vst <- varianceStabilizingTransformation(dds_for_vst) %>%
  assay() %>%
  as.data.frame()

# Add pseudocount to avoid counts = 0
pseudocount <- min(vst[vst > 0])/10  
vst <- vst + pseudocount
vst <- 2^(vst)

# Normalization by gene length
genes_length <- cts[match(intersect(rownames(vst), cts$Geneid), cts$Geneid), ]$Length
vst <- vst/(genes_length * 10^(-3))

# Centered Log2 Ratio (CLR)
clr <- log2(vst / exp(rowMeans(log(vst))))
```

```{r}
plot_CLR <- function(protein, ds_type) {
  protein_clr <- clr[protein, ]

  protein_clr <- protein_clr %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column("condition_time") %>%
    rename(value = protein) %>%
    separate(condition_time, into = c("condition", "time"), sep = "_") %>%
    mutate(time = as.numeric(time))
  
  # Plot
  ggplot(protein_clr, aes(x = time, y = value, color = condition, group = condition)) +
    geom_line(size = 1.2) +
    geom_point(size = 3) +
    theme_minimal() +
    scale_color_manual(
    values = c("infected" = "red",  
               "control" = "darkblue")   
    ) +
    ylim(-0.6, 0.8) +
    labs(
      title = paste("Defense system = ", ds_type),
      x = "Time post infection (min)",
      y = "CLR",
      color = "Condition"
    )
}
```

```{r, fig.height=16, fig.width=20}
plots <- list()

for (i in rownames(ds)) {
  plots[[i]] <- plot_CLR(ds[i, ]$protein_in_syst, ds[i, ]$type)
}

wrap_plots(plots[1:13], ncol = 4)
```

```{r}
min(clr[ds$protein_in_syst, ])
```

DESEQ + VOLCANO PLOT (control vs infected)

```{r}
# columns of cnt_matrix to select
cols <- c("control_0", "control_15", "control_30", "control_45", "control_60", "infected_0", "infected_15", "infected_30", "infected_45", "infected_60")


# construction of DESeq dataset
coldata <- data.frame(
  row.names = cols,
  condition = factor(c("control", "control", "control", "control", "control", "infected", "infected", "infected", "infected", "infected"))
)

countData <- round(cnt_matrix[,cols])

dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = coldata,
                              design = ~ condition)

# differential expression analysis
dds <- DESeq(dds)
res <- as.data.frame(results(dds, alpha = 0.1, pAdjustMethod = "fdr"))

# label for defense genes 
labels <- rownames(res) %>%
  as.data.frame() %>%
  `colnames<-`("protein_in_syst") %>%
  left_join(ds, by = "protein_in_syst") %>%
  mutate(label = ifelse(is.na(type), "", type)) %>%
  pull(label)

# add column labels (character and logical)
res <- mutate(res, label=labels)
res <- mutate(res, ds = factor(res$label != ""))

# plot -Log10 FDR vs Log fold change
plot <- ggplot(res, aes(x = log2FoldChange, y = -log10(pvalue), color = ds)) +
  geom_point(data = subset(res, ds == "FALSE"), color = "grey", alpha = 0.3) +
  geom_point(data = subset(res, ds == "TRUE"), color = "darkgreen") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +
  geom_label_repel(data = subset(res, ds == "TRUE" & padj < 0.05),
      aes(label = label), 
      size = 3, 
      max.overlaps = Inf, 
      show.legend = NA,
      colour = "black"
) +
  xlim(-5, 5) +
  ylim(0, 10) +
  annotate("text", x=-3, y=10, label =  "control vs infected") +
  theme_bw()
```

```{r}
plot
```
