---
title: "PRJNA804221"
output: html_notebook
---

LOADING PACKAGES

```{r}
source("../load_packages.R")
```

LOADING FILES

```{r}
source("../load_files.R")

SRRs <- SRRs %>%
  mutate(State = ifelse(str_detect(Library.Name, "P"), "infected", "control"),
         condition = str_remove_all(Library.Name, "[TP]")) %>%
  separate(condition, into = c("Time", "rep"), sep = "-", remove = FALSE) %>%
  mutate(condition = paste0(Time, "_", State, "_", rep))

# WE SHOULD REMOVE 0_control_1, 15_control_1, 15_infected_1, 60_control_1 et 60_infected_1 because they have around 40 genes with CLR very far from the other replicates. They appear outside the clusters in the PCoA.

SRRs <- SRRs[!(SRRs$condition %in% c("0_control_1", "15_control_1", "15_infected_1", "60_control_1", "60_infected_1")),]
```

```{r}
# Create count matrixes for all genes + bacterial genes+ phage genes
source("../count_matrices.R")

# Quality control steps
source("../qc_steps.R")
```

CLR
```{r, fig.height=10, fig.width=16}
source("../CLR.R")
source("../CLR_control.R")
wrap_plots(plots, ncol = 3)
```

```{r}
# Construction of a distance matrix for PCoA
dist_matrix_clr <- vegdist(t(clr), method = "euclidean")

# Compute principal coordinate decomposition
pcoa_clr <- pcoa(dist_matrix_clr)

# Plot PCoA2 vs PCoA2
pcoa_df_clr <- data.frame(
  condition = rownames(pcoa_clr$vectors),
  Axis1 = pcoa_clr$vectors[, 1],
  Axis2 = pcoa_clr$vectors[, 2]
  )

pcoa_df_clr <- left_join(pcoa_df_clr, SRRs, by = "condition") 
pcoa_df_clr <- pcoa_df_clr %>%
  mutate(label = paste0(ifelse(State == "infected", "I", "C"), " ", Time))


ggplot(pcoa_df_clr, aes(x = Axis1, y = Axis2, color = State, label = label)) +
  geom_point(size = 4) +
  geom_text(vjust = -0.8, size = 3.5, color = "black") +
  scale_color_manual(
    values = c("infected" = "red",  
               "control" = "darkblue")   
  ) +
  theme_minimal() +
  labs(
    x = paste0("PCoA 1 (", round(pcoa_clr$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA 2 (", round(pcoa_clr$values$Relative_eig[2] * 100, 1), "%)"),
    color = "Condition")
```


COMPUTE CORRELATION BETWEEN DEFENSE SYSTEMS EXPRESSION AND BACTERIAL GROWTH / PHAGE GROWTH
```{r}
source("../correlation_ds_growth.R")
conditions <- c("infected", "control")

for (condition in conditions) {
  for (ds_ in unique(ds$type)) {
    save_correlation(ds_, median_growth_markers_clr, "ribosome", condition)
    save_correlation(ds_, median_struct_phage_clr, "phage", condition)
  }
}

```

