---
title: "PRJNA726266"
output: html_notebook
---
LOADING PACKAGES

```{r}
source("../load_packages.R")
```

LOADING FILES

```{r}
source("../load_files.R")

SRRs <- SRRs %>%
  mutate(Time = str_remove_all(infection_time, " min = no phage"))%>%
  mutate(Time = str_remove_all(Time, " min"))%>%
  mutate(rep = str_remove_all(Replicate_number, "experiment "))%>%
  mutate(Time = as.numeric(Time)) %>%
  mutate(condition = paste0(Time, "_", genotype, "_", rep))

```

```{r}
# Create count matrixes for all genes + bacterial genes+ phage genes
source("../count_matrices.R")

# Quality control steps
source("../qc_steps.R")
```

CLR
```{r, fig.height=15, fig.width=20}
source("../CLR.R")
source("../CLR_control.R")
wrap_plots(plots, ncol = 3)
```

```{r}
# Construction of a distance matrix for PCoA
dist_matrix_clr <- vegdist(t(clr), method = "euclidean")

# Compute principal coordinate decomposition
pcoa_clr <- pcoa(dist_matrix_clr)

# Plot PCoA2 vs PCoA2
pcoa_df_clr <- data.frame(
  condition = rownames(pcoa_clr$vectors),
  Axis1 = pcoa_clr$vectors[, 1],
  Axis2 = pcoa_clr$vectors[, 2]
  )

pcoa_df_clr <- left_join(pcoa_df_clr, SRRs, by = "condition")

ggplot(pcoa_df_clr, aes(x = Axis1, y = Axis2, color = Time, label = Time)) +
  geom_point(size = 4) +
  geom_text(vjust = -0.8, size = 3.5, color = "black") +
  theme_minimal() +
  labs(
    x = paste0("PCoA 1 (", round(pcoa_clr$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA 2 (", round(pcoa_clr$values$Relative_eig[2] * 100, 1), "%)"),
    color = "Condition")
```


```{r}
plot_CLR <- function(protein, ds_type) {
  protein_clr <- clr[protein, , drop = FALSE]

  protein_clr <- protein_clr %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column("time_rep") %>%
    separate(time_rep, into = c("time", "rep"), sep = "h_") %>%
    mutate(time = as.numeric(time)) %>%
    pivot_longer(
      cols = -c(time, rep),   
      names_to = "protein",
      values_to = "value"
    ) %>%
    group_by(time) %>%
    summarise(
      median = median(value, na.rm = TRUE),
      sd     = sd(value, na.rm = TRUE),
      .groups = "drop"
    )


  # Plot
  ggplot(protein_clr, aes(x = time, y = median)) +
    geom_errorbar(aes(ymin = median-sd, ymax = median+sd)) +
    geom_line(size = 1.2) +
    geom_point(size = 3) +
    theme_minimal() +
    ylim(-1, 1) +
    labs(
      title = paste("Defense system = ", ds_type),
      x = "Time post infection (min)",
      y = "median CLR"
    ) +
    theme(
      plot.title = element_text(size = 15, face = "bold"),      
      axis.title.x = element_text(size = 15),                 
      axis.title.y = element_text(size = 15),                
      axis.text.x = element_text(size = 16),                    
      axis.text.y = element_text(size = 16)                      
  )
}
```

```{r, fig.height=20, fig.width=20}
plots <- list()
for (ds_ in unique(ds$type)) {
  proteins <- ds %>% filter(type == ds_) %>% pull(protein_in_syst)
  plots[[ds_]] <- plot_CLR(proteins, ds_)
}

wrap_plots(plots, ncol = 4)
```


DESEQ + VOLCANO PLOT FUNCTION (control vs infected)

```{r}
deseq_volcano_c_i <- function(t) {
  # columns of cnt_matrix to select
  cols <- c("0h_1", "0h_2",
      paste0(t, "h_1"),
      paste0(t, "h_2")
    )
  
  # construction of DESeq dataset
  coldata <- data.frame(
    row.names = cols,
    condition = factor(c("control", "control", "infected", "infected"))
  )
  
  countData <- round(cnt_matrix[,cols]+1)
  
  dds <- DESeqDataSetFromMatrix(countData = countData,
                                colData = coldata,
                                design = ~ condition)
  
  # differential expression analysis
  dds <- DESeq(dds)
  res <- as.data.frame(results(dds, alpha = 0.1, pAdjustMethod = "fdr"))
  
  # label for defense genes 
  labels <- ds$type[match(rownames(res), ds$protein_in_syst)]
  labels[is.na(labels)] <- ""
  
  # add column labels (character and logical)
  res <- mutate(res, label=labels)
  res <- mutate(res, ds = factor(res$label != ""))
  res <- mutate(res, Gene_origin = cts$Gene_origin[match(rownames(res), cts$Geneid)])
  
  # plot -Log10 FDR vs Log fold change
  plot <- ggplot(res, aes(x = log2FoldChange, y = -log10(padj), color = ds)) +
    geom_point(data = subset(res, ds == "FALSE"), color = "grey", alpha = 0.3) +
    geom_point(data = subset(res, ds == "TRUE"), color = "darkgreen") +
    geom_point(data = subset(res, Gene_origin == "Phage"), color = "salmon") +
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +
    geom_label_repel(data = subset(res, ds == "TRUE" & padj < 0.05),
        aes(label = label), 
        size = 3, 
        max.overlaps = Inf, 
        show.legend = NA,
        colour = "black"
  ) +
    xlim(-10, 10) +
    ylim(0, 25) +
    annotate("text", x=-5, y=20, label = paste0(t, " h (C vs I)")) +
    theme_bw()


  return(plot)
}
```

```{r, fig.height=7, fig.width=16}
plot1 <- deseq_volcano_c_i(1 ) 
plot2 <- deseq_volcano_c_i(2 ) 
plot3 <- deseq_volcano_c_i(3 ) 

plot1 + plot2 + plot3 + plot_layout(nrow = 1) 
```
COMPUTE CORRELATION BETWEEN DEFENSE SYSTEMS EXPRESSION AND BACTERIAL GROWTH / PHAGE GROWTH
```{r}
source("../correlation_ds_growth.R")

  for (ds_ in unique(ds$type)) {
    save_correlation(ds_, median_growth_markers_clr, "ribosome")
    save_correlation(ds_, median_struct_phage_clr, "phage")
  }


```
