---
title: "PRJNA262612"
output: html_notebook
---


LOADING PACKAGES

```{r}
source("../load_packages.R")
```

LOADING FILES

```{r}
source("../load_files.R")

SRRs <- SRRs %>%
  mutate(State = ifelse(str_detect(Sample.Name, "Infected"), "infected", "control"),
         Time = as.numeric(str_extract(Sample.Name, "\\d+")), 
         Phosphate = case_when(
      str_detect(isolation_source, "NoPhosphate")    ~ "P-",
      str_detect(isolation_source, "PhosphateAdded") ~ "P+",
      TRUE                                           ~ "P"
    )
    )

SRRs <- SRRs %>%
  group_by(Time, State, Phosphate) %>%
  mutate(rep = row_number()) %>%
  ungroup() %>%
  mutate(condition = paste0(Time, "_", State, "_", Phosphate, "_", rep))
```


```{r}
# Create count matrixes for all genes + bacterial genes+ phage genes
source("../count_matrices.R")

# Quality control steps
source("../qc_steps.R")
```


CLR
```{r}
# Computes CLR for all genes, ribosome genes and structural phage genes
source("../CLR.R")
```

```{r}
# Construction of a distance matrix for PCoA
dist_matrix_clr <- vegdist(t(clr), method = "euclidean")

# Compute principal coordinate decomposition
pcoa_clr <- pcoa(dist_matrix_clr)

# Plot PCoA2 vs PCoA2
pcoa_df_clr <- data.frame(
  condition = rownames(pcoa_clr$vectors),
  Axis1 = pcoa_clr$vectors[, 1],
  Axis2 = pcoa_clr$vectors[, 2]
  )

pcoa_df_clr <- left_join(pcoa_df_clr, SRRs, by = "condition")

ggplot(pcoa_df_clr, aes(x = Axis1, y = Axis2, color = Time, label = Time)) +
  geom_point(size = 4) +
  geom_text(vjust = -0.8, size = 3.5, color = "black") +
  theme_minimal() +
  labs(
    x = paste0("PCoA 1 (", round(pcoa_clr$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA 2 (", round(pcoa_clr$values$Relative_eig[2] * 100, 1), "%)"),
    color = "Condition")
```


PLOT DEFENSE SYSTEMS CLR vs GROWTH MARKERS CLR

```{r, fig.height=13, fig.width=20}
source("../plot_ds_vs_growth.R")

conditions <- c("infected_P", "control_P", "infected_P-", "control_P-", "infected_P+", "control_P+")
plots_list <- list()

for (cond in conditions) {
  plots_cond <- list()
  for (ds_ in unique(ds$type)) {
    proteins <- ds %>% filter(type == ds_) %>% pull(protein_in_syst)
    plots_cond[[ds_]] <- plot_ds_vs_growth(proteins, ds_, median_growth_markers_clr, "ribosome genes", condition_filter = cond)
  }
  plots_list[[cond]] <- wrap_plots(plots_cond, ncol = 3)
}

plots_list$infected_P
plots_list$control_P
plots_list$'infected_P-'
plots_list$'control_P-'
plots_list$'infected_P+'
plots_list$'control_P+'
```
