library(Biostrings)
library(rtracklayer)
library(tidyr)
library(dplyr)
library(stringr)
library(seqinr)
source("order_proteins.R")
source("add_gene_id_ds.R")

#order_proteins("protein.faa", "cds_from_genomic.fna")
add_gene_id_ds("defense_systems.tsv", "genomic.gff")