---
title: "PRJNA633474"
output: html_notebook
---


LOADING PACKAGES

```{r}
source("../load_packages.R")
```

LOADING FILES

```{r}
source("../load_files.R")

SRRs <- SRRs %>%
  mutate(State = ifelse(str_detect(source_name, "infected"), "infected", "control"),
  Time = case_when(
      str_detect(Time, "h")   ~ as.numeric(str_remove(Time, "\\s*h")) * 60,
      str_detect(Time, "min") ~ as.numeric(str_remove(Time, "\\s*min"))), 
  condition = paste0(Time, "_", State))
```


```{r}
# Create count matrixes for all genes + bacterial genes+ phage genes
source("../count_matrices.R")

# Quality control steps
source("../qc_steps.R")
```

CLR
```{r, fig.height=15, fig.width=20}
# Computes CLR for all genes, ribosome genes and structural phage genes
source("../CLR.R")
source("../CLR_control.R")
wrap_plots(plots, ncol = 3)
```

```{r}
# Construction of a distance matrix for PCoA
dist_matrix_clr <- vegdist(t(clr), method = "euclidean")

# Compute principal coordinate decomposition
pcoa_clr <- pcoa(dist_matrix_clr)

# Plot PCoA2 vs PCoA2
pcoa_df_clr <- data.frame(
  condition = rownames(pcoa_clr$vectors),
  Axis1 = pcoa_clr$vectors[, 1],
  Axis2 = pcoa_clr$vectors[, 2]
  )

pcoa_df_clr <- left_join(pcoa_df_clr, SRRs, by = "condition")

ggplot(pcoa_df_clr, aes(x = Axis1, y = Axis2, color = State, label = Time)) +
  geom_point(size = 4) +
  geom_text(vjust = -0.8, size = 3.5, color = "black") +
  scale_color_manual(values = c("infected" = "red", "control" = "blue")) +
  theme_minimal() +
  labs(
    x = paste0("PCoA 1 (", round(pcoa_clr$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA 2 (", round(pcoa_clr$values$Relative_eig[2] * 100, 1), "%)"),
    color = "Condition")
```
COMPUTE CORRELATION BETWEEN DEFENSE SYSTEMS EXPRESSION AND BACTERIAL GROWTH / PHAGE GROWTH
```{r}
# no ds genes reported by defense finder
source("../correlation_ds_growth.R")
conditions <- c("infected", "control")

for (condition in conditions) {
  for (ds_ in unique(ds$type)) {
    save_correlation(ds_, median_growth_markers_clr, "ribosome", condition)
    save_correlation(ds_, median_struct_phage_clr, "phage", condition)
  }
}
```

